[package]
name = "from-user"
version = "0.2.0"
edition = "2024"
authors = ["Devanshu Sharma <sharma.devanshu089@gmail.com>"]
description = "A small Rust crate for taking input. Highly Simplified"
license = "MIT OR Apache-2.0"

[dependencies]

#v0.1.0 Basic Working
#v0.2.0 Added ability for number
